title: tophackr.com
author: Alexandr Musikhin
description: I make useless projects.
avatar: 'assets/avatar.png'
baseurl: ''
url: 'https://tophackr.com'

social-network:
  email: 'contact@tophackr.com'
  twitter: tophackr_com

comments_site_id: xQFIyFjK #t3lKNYDb

collections:
  projects:
    output: true
    permalink: /p/:title

defaults:
  - scope:
      path: ''
      type: projects
    values:
      layout: project

markdown: kramdown
timezone: Europe/Moscow
encoding: utf-8
permalink: slug
exclude:
  - '.gitignore'
  - '.gitattributes'
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
