title: Alexandr Musikhin
description: Passionate about developing innovative solutions and tools. I am open for cooperation and exchange of experience.
baseurl: ''
url: 'https://tophackr.com'

author: tophackr
twitter:
  username: tophackr_com
  card: summary

social-network:
  email: 'contact@tophackr.com'

collections:
  projects:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ''
      type: projects
    values:
      toc: true
      layout: project
  - scope:
      path: ''
    values:
      image: /assets/avatar.png

toc:
  max_level: 1
  list_class: flex flex-row flex-wrap justify-center gap-2
  item_class: link-primary
  item_prefix: ''


markdown: kramdown
timezone: Europe/Moscow
encoding: utf-8
locale: en
exclude:
  - '.gitignore'
  - '.gitattributes'
  - README.md
  - COMMIT_CONVENTION.md
  - Gemfile
  - Gemfile.lock
  - CNAME
