title: tophackr.com
description: There must be a description.
baseurl: ''
url: 'https://tophackr.com'

collections:
  projects:
    output: true
    permalink: /:title

markdown: kramdown
timezone: Europe/Moscow
encoding: utf-8
permalink: slug
#exclude: ['.gitignore']
