title: tophackr.com
author: Alexandr Musikhin
description: I make useless projects.
avatar: 'assets/avatar.png'
baseurl: ''
url: 'https://tophackr.com'

social-network:
  email: 'contact@tophackr.com'
  twitter: tophackr_com

collections:
  projects:
    output: true
    permalink: /p/:title

defaults:
  - scope:
      path: ''
      type: projects
    values:
      toc: true
      layout: project

toc:
  max_level: 1
  list_class: flex flex-row flex-wrap justify-center gap-2
  item_class: link-primary
  item_prefix: ''

markdown: kramdown
timezone: Europe/Moscow
encoding: utf-8
permalink: slug
exclude:
  - '.gitignore'
  - '.gitattributes'
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
